#!name=Game Login Mock (QA)
#!desc=Mock login API + capture userName (No Cache)
#!system=ios

[Script]
Game_Login_Capture = type=http-request, pattern=^http:\/\/103\.178\.234\.177:83\/api\.php(\?.*)?$, requires-body=true, max-size=-1, timeout=60, script-path=https://raw.githubusercontent.com/connguoihaha/fakelogin/refs/heads/main/fake_login.js

Game_Login_Mock     = type=http-response, pattern=^http:\/\/103\.178\.234\.177:83\/api\.php(\?.*)?$, requires-body=true, max-size=-1, timeout=60, script-path=https://raw.githubusercontent.com/connguoihaha/fakelogin/refs/heads/main/fake_login.js

[MITM]
hostname = %APPEND% 103.178.234.177
